import sys
import os

# Load config
if "--configfile" in sys.argv:
    i = sys.argv.index("--configfile")
    config_path = sys.argv[i + 1]
    configfile: config_path
else:
    config_path = "config/config.yml"
    configfile: config_path

DATA_DIR = config['DATA_DIR']
ANALYSIS_DIR = config['ANALYSIS_DIR']
PLOTS_DIR = config['PLOTS_DIR']
LOG_DIR = config['LOG_DIR']
LOG_LEVEL = config['LOG_LEVEL']

CELL_TYPES = config['CELL_TYPES']

# Load rules
include: "rules/sencid.smk"

rule all:
    input:
        os.path.join(ANALYSIS_DIR, "counts.h5ad"),
        os.path.join(ANALYSIS_DIR, "counts_SenCID_results.txt"),
        os.path.join(PLOTS_DIR, "SenCID_predictions.pdf")

rule assemble_anndata:
    input:
        count_files = expand(os.path.join(DATA_DIR, "3_{cell_type}_all_results_annot.txt"), cell_type=CELL_TYPES)
    output:
        anndata = os.path.join(ANALYSIS_DIR, "counts.h5ad"),
        # save as txt file for SenCID - it cannot load h5ad object created by newer versions of scanpy
        # index is Gene_name -> rows with NaNs are removed
        txt = os.path.join(ANALYSIS_DIR, "counts.txt")
    log:
        os.path.join(LOG_DIR, "assemble_anndata.log")
    conda:
        "envs/data.yaml"
    shell:
        """
        python workflow/scripts/assemble_anndata.py \
            {input.count_files} \
            --output_h5ad {output.anndata} \
            --output_txt {output.txt} \
            --log {log} \
            --log-level {LOG_LEVEL} \
            2>&1 | tee {log}
        """